@startyaml
object: "F4101"
filter: 
  - connection: null
    colunm: "IMPRP1"
    operator: "="
    value: "A01"
  - connection: "AND"
    colunm: "IMPRP2"
    operator: "="
    value: "B01"
order:
  - colunm: "IMITM"
    sort: "A"
return: 
  - IMITM
  - IMDSC1
  - IMDSC2
@endyaml